stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./gradlew build

deploy:
  stage: deploy
  script:
    - scp -i ~/.ssh/sejongpeer-server-key.pem build/libs/*.jar ubuntu@haiseongworld.com:8080/~
    - ps -ef | grep "java -jar server-0.0.1-SNAPSHOT.jar" | head -n 1 | awk '{print $2}' | xargs kill
    - nohup java -jar server-0.0.1-SNAPSHOT.jar &
    - echo "server reboot!"
