#name: Deploy to AWS EC2 Instance
#
#on:
#  push:
#    branches:
#      - main
#
#env:
#  SSH_KNOWN_HOSTS: |
#    haiseongworld.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdUU4MpfkY/QHSfjJxzWCx9wT9JbfdbPSOOvBzRpym4E9LHnn61no+19zOcrK0nlU2UBN4DIVZOLJiahMkMiXlMv8TOBCH+dAheTw4LE60BQOQVjrNa9utMZefc1geIFEHGgL0dJtilhCK65DWJofDgbBrqXn2BGQ87pwocsZblR+VgMi0PDsHhsF4nyXlFiqpMDWZD0GTky/WSCzG2RmEeJ+VQD/zCUkWLadUb6yOhsvPP3BXBV+ZJSB+SHUR0M4xN+AT0CdVWwJvmJNJtr/+dqJu6ozWcJNkBGOSIyfj67SeEpvBykTowe/872ph3dkJFNBKE/tdr2iclfZbDhfXPUVq80IdPCAiewdv62JQjZT/YDod/rgk2fX29T8YMhYppDGpnuA8cGQo2m4Uu/LpIJEUIdgwYNqacajsf7lgUtnDua8sbWqN+0kMvT5RW/w7ddHxw8Bk34SK19pAqBv3wLPR1C6KR6QQVdH6k/yiS4p4f3ELj5lurKFmQY0r0Ec=
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Use SSH key to connect to the server
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Copy files to the server
#        uses: appleboy/scp-action@master
#        with:
#          host: haiseongworld.com
#          username: {SSH_USERNAME}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "/path/to/local/files/*"
#          target: "/path/to/remote/directory/"
#


name: Java CI with Gradle

on: [push, pull_request]

env:
  SSH_KNOWN_HOSTS: |
    haiseongworld.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdUU4MpfkY/QHSfjJxzWCx9wT9JbfdbPSOOvBzRpym4E9LHnn61no+19zOcrK0nlU2UBN4DIVZOLJiahMkMiXlMv8TOBCH+dAheTw4LE60BQOQVjrNa9utMZefc1geIFEHGgL0dJtilhCK65DWJofDgbBrqXn2BGQ87pwocsZblR+VgMi0PDsHhsF4nyXlFiqpMDWZD0GTky/WSCzG2RmEeJ+VQD/zCUkWLadUb6yOhsvPP3BXBV+ZJSB+SHUR0M4xN+AT0CdVWwJvmJNJtr/+dqJu6ozWcJNkBGOSIyfj67SeEpvBykTowe/872ph3dkJFNBKE/tdr2iclfZbDhfXPUVq80IdPCAiewdv62JQjZT/YDod/rgk2fX29T8YMhYppDGpnuA8cGQo2m4Uu/LpIJEUIdgwYNqacajsf7lgUtnDua8sbWqN+0kMvT5RW/w7ddHxw8Bk34SK19pAqBv3wLPR1C6KR6QQVdH6k/yiS4p4f3ELj5lurKFmQY0r0Ec=

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Copy jar file to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          scp build/libs/*.jar ubuntu@haiseongworld.com:~
    - name: Kill Running Process
      run: ps -ef | grep "java -jar server-0.0.1-SNAPSHOT.jar" | head -n 1 | awk '{print $2}' | xargs kill
    - name: Run new jar file
      run: nohup java -jar server-0.0.1-SNAPSHOT.jar &
