name: Java CI with Gradle

on: [push, pull_request]

env:
  SSH_KNOWN_HOSTS: |
    # haiseongworld.com:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
    haiseongworld.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICGOhRIZ043zSmqgzDvN5wSCV2N1W+YFmKUkw+GGan9F
    # haiseongworld.com:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
    haiseongworld.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdUU4MpfkY/QHSfjJxzWCx9wT9JbfdbPSOOvBzRpym4E9LHnn61no+19zOcrK0nlU2UBN4DIVZOLJiahMkMiXlMv8TOBCH+dAheTw4LE60BQOQVjrNa9utMZefc1geIFEHGgL0dJtilhCK65DWJofDgbBrqXn2BGQ87pwocsZblR+VgMi0PDsHhsF4nyXlFiqpMDWZD0GTky/WSCzG2RmEeJ+VQD/zCUkWLadUb6yOhsvPP3BXBV+ZJSB+SHUR0M4xN+AT0CdVWwJvmJNJtr/+dqJu6ozWcJNkBGOSIyfj67SeEpvBykTowe/872ph3dkJFNBKE/tdr2iclfZbDhfXPUVq80IdPCAiewdv62JQjZT/YDod/rgk2fX29T8YMhYppDGpnuA8cGQo2m4Uu/LpIJEUIdgwYNqacajsf7lgUtnDua8sbWqN+0kMvT5RW/w7ddHxw8Bk34SK19pAqBv3wLPR1C6KR6QQVdH6k/yiS4p4f3ELj5lurKFmQY0r0Ec=
    # haiseongworld.com:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
    haiseongworld.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDs4SB7EKsCAl/9It3bNplDyKKc2MDchEoXkF2g2vPqtR9M2Ko99Rpt5daBiVtD33+1cnhl0JyAP73FshFcgk18=

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Copy jar file to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          scp build/libs/*.jar ubuntu@haiseongworld.com:~
        options: '-o StrictHostKeyChecking=no'
    - name: Kill Running Process
      run: ps -ef | grep "java -jar server-0.0.1-SNAPSHOT.jar" | head -n 1 | awk '{print $2}' | xargs kill
    - name: Run new jar file
      run: nohup java -jar server-0.0.1-SNAPSHOT.jar &
